
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#282c34"
blue = "#61afef"
cyan = "#2bbac5"
green = "#89ca78"
magenta = "#d55fde"
red = "#ef596f"
white = "#abb2bf"
yellow = "#e5c07b"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#2bbac5"
green = "#89ca78"
magenta = "#d55fde"
red = "#ef596f"
white = "#abb2bf"
yellow = "#e5c07b"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Super"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[scrolling]
history = 10000

[window]
option_as_alt = "Both"

[general]
import = ["~/.alacritty-font.toml"]
